In [1]:
len?

In [2]:
L = [1, 2, 3]

In [1]:
import numpy as np

In [4]:
x1 = np.random.randint(10, size=6)
print(x1)

[7 2 7 8 3 4]


In [6]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[5, 3, 5, 2],
       [4, 9, 8, 0],
       [0, 8, 4, 4]])

In [7]:
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[2, 1, 6, 3, 1],
        [9, 9, 7, 2, 1],
        [5, 2, 4, 7, 8],
        [6, 5, 3, 1, 9]],

       [[4, 6, 2, 6, 8],
        [3, 2, 3, 6, 7],
        [6, 0, 9, 4, 9],
        [5, 1, 6, 3, 2]],

       [[1, 4, 8, 3, 4],
        [6, 0, 4, 4, 0],
        [0, 1, 3, 7, 8],
        [2, 0, 5, 7, 5]]])

In [13]:
x3[1,0,0]

4

In [9]:
print(x3.itemsize)
print(x3.nbytes)

8
480


In [14]:
print(x2)

[[5 3 5 2]
 [4 9 8 0]
 [0 8 4 4]]


In [24]:
x2_sub = x2[::2,::2]
x2_sub

array([[10,  5],
       [ 0,  4]])

In [25]:
x2_sub[0, 0] = 5
print(x2_sub)

[[5 5]
 [0 4]]


In [26]:
x2

array([[5, 3, 5, 2],
       [4, 9, 8, 0],
       [0, 8, 4, 4]])

In [38]:
x = np.array([1, 2, 3, 4, 5, 6])

In [43]:
print(x)

[1 2 3 4 5 6]


In [50]:
x = x.reshape((2,3))

In [62]:
x[0]

array([1, 2, 3])

In [67]:
x[1,0]

4

In [53]:
y = x[np.newaxis, :]
y

array([[[1, 2, 3],
        [4, 5, 6]]])

In [65]:
y[0,1,0]

4

In [69]:
y.shape

(1, 2, 3)

In [70]:
x.shape

(2, 3)

In [71]:
z = x[: np.newaxis]

In [75]:
z[1,0]

4

In [73]:
z.shape

(2, 3)

In [88]:
x = np.array((1, 2, 3))
y = np.array((4, 5, 6))
z = np.concatenate((x, y))
z.shape

(6,)

In [91]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [93]:
a = np.arange(6)

In [96]:
a % 2

array([0, 1, 0, 1, 0, 1])